### ISSUE TITLE
feat: Support schema discovery for CustomFields

### ISSUE THREAD

**Issue by jeffgeorge** [MeltanoLabs/tap-jira#99]
To me (and likely others) Jira data without Custom Fields is not incredibly useful, and it appears based on investigation there is presently no way through configuration alone to use this tap to pull Custom Fields.

Specifically, I've looked through the following:
- https://github.com/MeltanoLabs/tap-jira/issues/58 - Old hardcoded customfield definitions cause conflicts if your customfields are configured differently, which they almost certainly will be
- https://github.com/MeltanoLabs/tap-jira/pull/90 - Old hardcoded customfield definitions were removed, with note that "Custom fields should be handled in a dynamic schema discovery way in the future"
- https://discuss.meltano.com/t/16276648/hey-everyone-i-m-trying-to-use-the-tap-jira-with-target-bigq - No amount of custom catalog, schema, or select overrides let you intentionally pull customfield data (coincidentally, I independently tried all of the options this user did to the same outcome before finding this discussion post)
- https://discuss.meltano.com/t/22876814/hey-tap-jira-stopped-to-work-for-me-because-one-custom-field - We can't seemingly exclude customfields from the issue stream, resulting in a _huge_ warning in your stdout unless you change tweak your log level to suppress them

I came to the same conclusion as Jean-Baptiste in the first [Discussion Thread](https://discuss.meltano.com/t/16276648/hey-everyone-i-m-trying-to-use-the-tap-jira-with-target-bigq), that the only option is to maintain a fork, and add your customfield definitions to the issueStream class yourself, but I would _vastly_ prefer not having to fork this tap entirely as it appears to still be maintained.

Assuming this research is all accurate, what's the plan for how to implement intentional support for arbitrary customfields? I'm happy to jump in and help build this, but I'd like some kind of direction of what the maintainers had in mind, specifically based on the comment in #90.

Assuming the research is _not_ accurate, we need to update documentation to explain how to define your customfields properly, and possibly also document how to exclude customfields you don't care about so it doesn't pollute the execution log with warnings.

**Comment by jeffgeorge** [comment]
In looking through other modules, I found that @edgarrmondragon's [tap-zendesk](https://github.com/edgarrmondragon/tap-zendesk/tree/main) handles this by adding the optional [additional_parameters](https://sdk.meltano.com/en/latest/classes/typing/singer_sdk.typing.ObjectType.html) param [to the user_fields property in the stream definition](https://github.com/edgarrmondragon/tap-zendesk/blob/main/tap_zendesk/streams.py#L355-L358). This results in being able to define custom schema in the `meltano.yml` like this:

```
    schema:
      users:
        user_fields:
          type: object
          properties:
            test_custom_field:
              type: [string, "null"]
            test_pii_field:
              type: [integer, "null"]
```

...which would be _perfect_ for the use-case I'd like to see solved.

I tried adding `additional_properties=True` to the bottom of the fields property definition, and then defined a customfield like this:

```
    schema:
      issues:
        fields:
          type: object
          properties:
            customfield_10001: # "Story Points" (float)
              type: [number, "null"]
```

But it didn't work: no (new) errors / warnings, and no new field created. This _feels_ like the right track, though it wouldn't clean up the spam of warnings to the log.
